version: '3.8'

services:
  web:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: fastapi_app
    environment:
      DOCKER_ENV: .env
    ports:
      - '8000:8000'
    #depends_on:
    #  - db
    volumes:
      - $SENTENCE_TRANSFORMERS_DIR:$SENTENCE_TRANSFORMERS_HOME

  db:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - docker.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      

#  minio:
#    image: minio/minio
#    container_name: minio
#    env_file:
#      - docker.env
#    ports:
#      - '9000:9000'
#      - '9001:9001'
#    command: server /data --console-address ":9001"

  ocr:
    build:
      context: ocr
    env_file:
     - docker.env
    volumes:
      - $OCR_MODELS:/ocr_models/model
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: 1
    #          capabilities: [gpu]
  yolo:
    build:
      context: yolo
    container_name: yolo
    environment:
      DOCKER_ENV: docker.env
    ports:
      - '8000:8000'
    env_file:
      - docker.env
    volumes:
      - $YOLO_DIR:/yolo_dir
volumes:
  postgres_data:
